'use client';
import { useState, useEffect, useMemo } from 'react';
import { motion } from 'framer-motion';
import { X, RefreshCw } from 'lucide-react';
interface P { isOpen: boolean; onClose?: () => void; message?: string; }
export function LoadingWithGames({ isOpen, onClose, message = 'Processing...' }: P) {
  const [g, setG] = useState<'tictactoe' | 'memory'>('tictactoe');
  const [w, setW] = useState(0);
  const [logs, setLogs] = useState(['[ML] Init pipeline...', '[ML] Load 42k samples...', '[ML] Warmup tensor cores...']);
  const [ep, setEp] = useState(1);
  const [dismissed, setDismissed] = useState(false);
  useEffect(() => { if (!isOpen) { setDismissed(false); setEp(1); } }, [isOpen]);
  useEffect(() => {
    if (!isOpen || dismissed) return;
    const iv = setInterval(() => {
      const loss = Math.max(0.04, 0.45 - ep * 0.006).toFixed(3);
      const acc = Math.min(0.99, 0.72 + ep * 0.005).toFixed(2);
      const steps = ['tokenizing code', 'ranking fixes', 'checking edge cases', 'compressing context', 'validating output'];
      const nl = `[Epoch ${ep}/50] ${steps[ep % steps.length]} • loss:${loss} acc:${acc}`;
      setLogs((p) => [...p.slice(-7), nl]);
      setEp((e) => (e >= 50 ? 1 : e + 1));
    }, 850);
    return () => clearInterval(iv);
  }, [isOpen, dismissed, ep]);
  const win = () => { setW((ww) => ww + 1); setTimeout(() => setG((x) => (x === 'tictactoe' ? 'memory' : 'tictactoe')), 1000); };
  if (!isOpen || dismissed) return null;
  return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-4"><motion.div initial={{ opacity: 0, scale: 0.96, y: 20 }} animate={{ opacity: 1, scale: 1, y: 0 }} className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl max-w-lg w-full overflow-hidden shadow-2xl"><div className="flex items-center justify-between px-5 py-3.5 border-b border-[var(--border)] bg-[var(--bg-elevated)]/50"><div className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-[var(--accent-orange)] animate-pulse"/><span className="font-mono text-sm font-bold tracking-wider text-[var(--accent-orange)]">{message}</span></div><button onClick={() => { setDismissed(true); onClose?.(); }} className="text-[var(--text-muted)] hover:text-white" aria-label="Close loading game modal"><X size={18}/></button></div><div className="p-4 border-b border-[var(--border)] bg-black/40 font-mono text-[10px] h-32 overflow-hidden relative"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-[var(--accent-cyan)] to-transparent animate-pulse"/><div className="text-[var(--accent-cyan)] mb-1 text-[9px] uppercase tracking-widest">TRAINING MACHINE LOGS</div>{logs.map((l,i)=><div key={`${l}-${i}`} className="text-[var(--text-muted)] opacity-90">{l}</div>)}<div className="text-[var(--success)] mt-1">... optimizer.step() • awaiting response</div></div><div className="p-5"><div className="flex items-center justify-between mb-3"><div><span className="text-sm font-bold">Sambil menunggu, main game dulu?</span> <span className="ml-2 text-[10px] px-2 py-0.5 rounded bg-[var(--accent-orange)]/10 text-[var(--accent-orange)]">2 GAMES</span></div><div className="text-xs text-[var(--text-muted)]">Wins: {w}</div></div><div className="flex gap-2 mb-4"><button onClick={()=>setG('tictactoe')} className={`flex-1 py-1.5 text-xs rounded-xl border ${g==='tictactoe'?'bg-[var(--accent-orange)]/10 border-[var(--accent-orange)] text-[var(--accent-orange)]':'border-[var(--border)]'}`}>Tic-Tac-Toe</button><button onClick={()=>setG('memory')} className={`flex-1 py-1.5 text-xs rounded-xl border ${g==='memory'?'bg-[var(--accent-orange)]/10 border-[var(--accent-orange)] text-[var(--accent-orange)]':'border-[var(--border)]'}`}>Memory Match</button></div><div className="bg-[var(--bg-elevated)] rounded-xl p-3 border border-[var(--border)] min-h-[170px] flex items-center justify-center">{g==='tictactoe'?<Tic onWin={win}/>:<Mem onWin={win}/>}</div></div><div className="px-5 py-3 border-t border-[var(--border)] text-[10px] text-center text-[var(--text-muted)]">Dev-ToolsBox • aesthetic loading mode</div></motion.div></div>;
}
function Tic({ onWin }: { onWin: (w: string) => void }) { const [b,setB]=useState<(string|null)[]>(Array(9).fill(null)); const [x,setX]=useState(true); const [w,setW]=useState<string|null>(null); const cw=(s:(string|null)[])=>{const ls=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]; for(const l of ls){const [a,bb,c]=l; if(s[a]&&s[a]===s[bb]&&s[a]===s[c])return s[a];} return null;}; const cl=(i:number)=>{if(b[i]||w)return; const nb=[...b]; nb[i]=x?'X':'O'; setB(nb); const ww=cw(nb); if(ww){setW(ww); onWin(ww);} else if(!nb.includes(null)){setW('Draw'); onWin('Draw');} else setX(!x);}; const rs=()=>{setB(Array(9).fill(null)); setX(true); setW(null);}; return <div className="p-4"><div className="grid grid-cols-3 gap-1 w-48 mx-auto mb-3">{b.map((c,i)=><button key={i} onClick={()=>cl(i)} className="w-14 h-14 bg-[var(--bg-elevated)] border border-[var(--border)] text-2xl font-bold flex items-center justify-center" disabled={!!c||!!w}>{c}</button>)}</div><div className="text-center text-xs text-[var(--text-muted)]">{w?`Winner: ${w}`:`Next: ${x?'X':'O'}`}</div><button onClick={rs} className="mt-2 text-xs flex items-center gap-1 mx-auto text-[var(--accent-cyan)]"><RefreshCw size={12}/> Reset</button></div>; }
function Mem({ onWin }: { onWin: () => void }) { const cs = useMemo(() => { const em=['🍕','🚀','🐱','🌟','🎮','🔥','🍔','🎸']; return [...em,...em].sort(()=>Math.random()-0.5); }, []); const [fl,setFl]=useState<number[]>([]); const [mt,setMt]=useState<number[]>([]); const [mv,setMv]=useState(0); const flp=(i:number)=>{if(fl.length===2||mt.includes(i)||fl.includes(i))return; const nf=[...fl,i]; setFl(nf); if(nf.length===2){setMv(m=>m+1); const [a,b]=nf; if(cs[a]===cs[b]){const nm=[...mt,a,b]; setMt(nm); setFl([]); if(nm.length===cs.length)setTimeout(()=>onWin(),600);}else setTimeout(()=>setFl([]),900);}}; return <div><div className="text-center text-xs mb-2 text-[var(--text-muted)]">Moves: {mv}</div><div className="grid grid-cols-4 gap-1 w-52 mx-auto">{cs.map((e,i)=><button key={i} onClick={()=>flp(i)} className={`w-12 h-12 text-2xl flex items-center justify-center rounded-lg border ${fl.includes(i)||mt.includes(i)?'bg-[var(--accent-orange)]/10 border-[var(--accent-orange)]':'bg-[var(--bg-elevated)] border-[var(--border)]'}`}>{fl.includes(i)||mt.includes(i)?e:'❓'}</button>)}</div><div className="text-center text-[10px] mt-2 text-[var(--text-muted)]">Match pairs!</div></div>; }
