'use client';
import { useState } from 'react';
import { Globe, Download, Code2, Loader2, AlertCircle } from 'lucide-react';
import JSZip from 'jszip';
interface SourceFile { name: string; content: string; type: string; }
export default function ViewSourcePage() {
  const [url, setUrl] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState<string|null>(null); const [source, setSource] = useState(''); const [files, setFiles] = useState<SourceFile[]>([]); const [activeTab, setActiveTab] = useState<'html'|'css'|'js'>('html');
  const extract = (html:string):SourceFile[] => { const ex:SourceFile[]=[]; let hc=html; const sm=html.match(/<style[^>]*>([\s\S]*?)<\/style>/gi); if(sm) sm.forEach((s,i)=>{const c=s.replace(/<\/?style[^>]*>/gi,''); ex.push({name:`inline-style-${i+1}.css`,content:c,type:'css'}); hc=hc.replace(s,`<!--inline-${i+1}-->`);}); const jm=html.match(/<script(?![^>]*src)[^>]*>([\s\S]*?)<\/script>/gi); if(jm) jm.forEach((s,i)=>{const c=s.replace(/<\/?script[^>]*>/gi,''); ex.push({name:`inline-script-${i+1}.js`,content:c,type:'js'}); hc=hc.replace(s,`<!--inline-${i+1}-->`);}); ex.unshift({name:'index.html',content:hc,type:'html'}); return ex; };
  const fetchSrc = async () => { if(!url.trim())return; setLoading(true);setError(null);setSource('');setFiles([]); try{ const r=await fetch(`/api/view-source?url=${encodeURIComponent(url.trim())}`); const d=await r.json(); if(!d.success)throw new Error(d.error||'fail'); setSource(d.html); setFiles(extract(d.html)); }catch(e:any){setError(e.message||'fetch fail');}finally{setLoading(false);} };
  const dlZip = async () => { if(!files.length)return; const z=new JSZip(); files.forEach(f=>z.file(f.name,f.content)); const b=await z.generateAsync({type:'blob'}); const l=document.createElement('a'); l.href=URL.createObjectURL(b); l.download=`source-${new URL(url).hostname.replace(/\./g,'-')}.zip`; l.click(); };
  const dlOne = (f:SourceFile) => { const b=new Blob([f.content],{type:'text/plain'}); const l=document.createElement('a'); l.href=URL.createObjectURL(b); l.download=f.name; l.click(); };
  const cf = files.find(f=>f.type===activeTab)||files[0];
  return (<main className="flex-1 max-w-[1100px] mx-auto w-full p-4 md:p-6"><div className="mb-6"><h1 className="font-display text-2xl font-bold flex items-center gap-3"><Globe className="text-[var(--accent-orange)]" /> View Source + Download</h1><p className="text-sm text-[var(--text-muted)] mt-1">Fetch any public website source code, extract resources, and download as ZIP or individual files.</p></div><div className="bg-[var(--bg-surface)] border border-[var(--border)] rounded-2xl p-5 mb-5"><div className="flex gap-3"><input type="url" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com" className="flex-1 bg-[var(--bg-elevated)] border border-[var(--border)] rounded-xl px-4 py-3 text-sm font-mono focus:outline-none focus:ring-1 focus:ring-[var(--accent-orange)]" /><button onClick={fetchSrc} disabled={loading||!url.trim()} className="shimmer flex items-center gap-2 px-6 py-3 bg-[var(--accent-orange)] text-white rounded-xl text-sm font-bold disabled:opacity-50">{loading?<Loader2 size={16} className="animate-spin"/>:<Code2 size={16}/>} {loading?'Fetching...':'Fetch Source'}</button></div>{error&&<div className="mt-3 flex items-center gap-2 text-sm text-[var(--critical)] bg-[var(--critical)]/5 p-2 rounded-lg"><AlertCircle size={15}/> {error}</div>}</div>{source&&<div className="space-y-4"><div className="flex items-center justify-between"><div className="text-sm text-[var(--text-muted)]">Source from: <span className="font-mono text-[var(--accent-cyan)]">{url}</span></div><button onClick={dlZip} className="flex items-center gap-2 px-4 py-2 bg-[var(--bg-elevated)] border border-[var(--border)] rounded-xl text-sm hover:border-[var(--accent-orange)]"><Download size={15}/> Download All as ZIP</button></div><div className="flex border-b border-[var(--border)]">{['html','css','js'].map(t=><button key={t} onClick={()=>setActiveTab(t as any)} className={`px-5 py-2 text-sm font-semibold capitalize ${activeTab===t?'border-b-2 border-[var(--accent-orange)] text-[var(--accent-orange)]':'text-[var(--text-muted)]'}`}>{t.toUpperCase()}</button>)}</div><div className="bg-[var(--bg-elevated)] rounded-2xl border border-[var(--border)] overflow-hidden"><div className="flex items-center justify-between px-4 py-2.5 border-b border-[var(--border)] bg-[var(--bg-surface)]"><div className="font-mono text-sm text-[var(--accent-cyan)]">{cf?.name||'source'}</div>{cf&&<button onClick={()=>dlOne(cf)} className="text-xs flex items-center gap-1.5 px-3 py-1 rounded-lg bg-[var(--bg-primary)] border border-[var(--border)] hover:border-[var(--accent-orange)]"><Download size={13}/> Download</button>}</div><pre className="p-4 overflow-auto text-xs font-mono max-h-[520px] whitespace-pre-wrap bg-[var(--bg-primary)]">{cf?.content||source}</pre></div></div>}</main>);
}
